package com.projecturanus.uranustech.api.builtin

import com.projecturanus.uranustech.MODID
import com.projecturanus.uranustech.common.material.UTWildcardMaterial
import net.minecraft.util.Identifier

val ANY_SALT = UTWildcardMaterial(Identifier(MODID, "any_salt"), SALT, MAGNESIUM_CHLORIDE, CALCIUM_CHLORIDE, ROCK_SALT, LITHIUM_CHLORIDE)
val ANY_STEEL = UTWildcardMaterial(Identifier(MODID, "any_steel"), H_S_L_A_STEEL, KNIGHTMETAL, STEEL, METEORIC_STEEL)
val ANY_IRON_STEEL = UTWildcardMaterial(Identifier(MODID, "any_iron_steel"), H_S_L_A_STEEL, KNIGHTMETAL, STEEL, METEORIC_STEEL)
val ANY_THAUMIC_CRYSTAL = UTWildcardMaterial(Identifier(MODID, "any_thaumic_crystal"), INFUSED_BALANCE, INFUSED_DULL, INFUSED_VIS, INFUSED_AIR, INFUSED_FIRE, INFUSED_EARTH, INFUSED_WATER, INFUSED_ENTROPY, INFUSED_ORDER)
val ANY_EMERALD = UTWildcardMaterial(Identifier(MODID, "any_emerald"), EMERADIC, EMERALD, AQUAMARINE, MORGANITE, HELIODOR, GOSHENITE, BIXBITE, MAXIXE)
val ANY_ASHES = UTWildcardMaterial(Identifier(MODID, "any_ashes"), VOLCANIC_ASHES, ASHES, DARK_ASHES)
val ANY_CARBON = UTWildcardMaterial(Identifier(MODID, "any_carbon"), CARBON, GRAPHENE, GRAPHITE)
val ANY_NORMAL_WOOD = UTWildcardMaterial(Identifier(MODID, "any_normal_wood"), WOOD, PEANUT_WOOD, BAMBOO, SKYROOT, WEEDWOOD)
val ANY_DIAMOND = UTWildcardMaterial(Identifier(MODID, "any_diamond"), DIAMANTINE, DIAMOND, DIAMOND_INDUSTRIAL, MANA_DIAMOND, ELVEN_DRAGONSTONE)
val ANY_CLAY = UTWildcardMaterial(Identifier(MODID, "any_clay"), CLAY, CLAY_BROWN)
val ANY_TREATED_WOOD = UTWildcardMaterial(Identifier(MODID, "any_treated_wood"), WOOD_SEALED, WOOD_POLISHED)
val ANY_COAL_CARBON = UTWildcardMaterial(Identifier(MODID, "any_coal_carbon"), CARBON, GRAPHENE, CHARCOAL, COAL, COAL_COKE, GRAPHITE)
val ANY_SILICON = UTWildcardMaterial(Identifier(MODID, "any_silicon"), SILICON)
val ANY_CALCITE = UTWildcardMaterial(Identifier(MODID, "any_calcite"), CHALK, CALCITE, DOLOMITE, MARBLE, LIMESTONE)
val ANY_IRON = UTWildcardMaterial(Identifier(MODID, "any_iron"), ENORI, PIG_IRON, WROUGHT_IRON, METEORITE, IRON, METEORIC_IRON)
val ANY_WOOD_OR_PLASTIC = UTWildcardMaterial(Identifier(MODID, "any_wood_or_plastic"), WOOD, WOOD_SEALED, WOOD_POLISHED, WOOD_RUBBER, BAMBOO, SKYROOT, WEEDWOOD, LIVINGWOOD, DREAMWOOD, SHIMMERWOOD, GREATWOOD, SILVERWOOD, PEANUT_WOOD, MARSHMALLOW, PLASTIC)
val ANY_SILICON_DIOXIDE = UTWildcardMaterial(Identifier(MODID, "any_silicon_dioxide"), SUNNY_QUARTZ, LAVENDER_QUARTZ, RED_QUARTZ, BLAZE_QUARTZ, SMOKEY_QUARTZ, MANA_QUARTZ, ELVEN_QUARTZ, NETHER_QUARTZ, GLASS, QUARTZ_BLACK, FLINT, CERTUS_QUARTZ, CHARGED_CERTUS_QUARTZ, FLUIX, SILICON_DIOXIDE, QUARTZITE)
val ANY_WOOD = UTWildcardMaterial(Identifier(MODID, "any_wood"), WOOD, WOOD_SEALED, WOOD_POLISHED, WOOD_RUBBER, BAMBOO, SKYROOT, WEEDWOOD, LIVINGWOOD, DREAMWOOD, SHIMMERWOOD, GREATWOOD, SILVERWOOD, PEANUT_WOOD, MARSHMALLOW)
val ANY_METAL = UTWildcardMaterial(Identifier(MODID, "any_metal"))
val ANY_DEFAULT_WOOD = UTWildcardMaterial(Identifier(MODID, "any_default_wood"), WOOD, PEANUT_WOOD)
val ANY_GARNET = UTWildcardMaterial(Identifier(MODID, "any_garnet"), ANDRADITE, UVAROVITE, ALMANDINE, GROSSULAR, PYROPE, SPESSARTINE)
val ANY_IRON_OR_STEEL = UTWildcardMaterial(Identifier(MODID, "any_iron_or_steel"), H_S_L_A_STEEL, ENORI, KNIGHTMETAL, STEEL, PIG_IRON, WROUGHT_IRON, METEORITE, IRON, METEORIC_IRON, METEORIC_STEEL)
val ANY_PRISMARINE = UTWildcardMaterial(Identifier(MODID, "any_prismarine"), PRISMARINE, PRISMARINE_DARK)
val ANY_COPPER = UTWildcardMaterial(Identifier(MODID, "any_copper"), COPPER, ANNEALED_COPPER)
val ANY_WAX = UTWildcardMaterial(Identifier(MODID, "any_wax"), WAX_PLANT, WAX_MAGIC, WAX_AMNESIC, WAX_SOULFUL, WAX, WAX_BEE, WAX_REFRACTORY, WAX_PARAFFIN)
val ANY_SAPPHIRE = UTWildcardMaterial(Identifier(MODID, "any_sapphire"), YELLOW_SAPPHIRE, ORANGE_SAPPHIRE, BLUE_SAPPHIRE, PURPLE_SAPPHIRE, RUBY, SAPPHIRE, GREEN_SAPPHIRE)
val ANY_QUARTZ = UTWildcardMaterial(Identifier(MODID, "any_quartz"), SUNNY_QUARTZ, LAVENDER_QUARTZ, RED_QUARTZ, BLAZE_QUARTZ, SMOKEY_QUARTZ, MANA_QUARTZ, ELVEN_QUARTZ, NETHER_QUARTZ, QUARTZ_BLACK, CERTUS_QUARTZ, CHARGED_CERTUS_QUARTZ, FLUIX, QUARTZITE)
val ANY_BRONZE = UTWildcardMaterial(Identifier(MODID, "any_bronze"))
val ANY_STONE = UTWildcardMaterial(Identifier(MODID, "any_stone"), STONE, CONCRETE, NETHERRACK, NETHER_BRICK, ENDSTONE, SPACE_STONE, MOON_STONE, MOON_TURF, MARS_STONE, MARS_SAND, UMBER, HOLYSTONE, LIVINGROCK, BETWEENSTONE, PITSTONE, REDROCK, GABBRO, KOMATIITE, BASALT, MARBLE, LIMESTONE, GREENSCHIST, BLUESCHIST, KIMBERLITE, QUARTZITE, GRANITE_RED, GRANITE_BLACK, GRANITE, ANDESITE, DIORITE, GRAVEL, GNEISS, GREYWACKE, SILTSTONE, RHYOLITE, MIGMATITE, CHERT, DACITE, SHALE, ECLOGITE, PRISMARINE, PRISMARINE_DARK, GREENSTONE, BLUESTONE, EPIDOTE)
val ANY_UNTREATED_WOOD = UTWildcardMaterial(Identifier(MODID, "any_untreated_wood"), SILVERWOOD, WOOD, PEANUT_WOOD, BAMBOO, SKYROOT, WEEDWOOD, LIVINGWOOD, DREAMWOOD, SHIMMERWOOD, GREATWOOD)
val ANY_GRAINS = UTWildcardMaterial(Identifier(MODID, "any_grains"), WHEAT, BARLEY, RYE, RICE, OAT, CORN)
val ANY_TUNGSTEN = UTWildcardMaterial(Identifier(MODID, "any_tungsten"), TUNGSTEN, TUNGSTEN_SINTERED)
val ANY_FLOUR_OR_GRAINS = UTWildcardMaterial(Identifier(MODID, "any_flour_or_grains"), POTATO, WHEAT, BARLEY, RYE, RICE, OAT, CORN)
val ANY_GLOWSTONE = UTWildcardMaterial(Identifier(MODID, "any_glowstone"), GLOWSTONE, GLOWSTONE_CERES, GLOWSTONE_IO, GLOWSTONE_ENCELADUS, GLOWSTONE_PROTEUS, GLOWSTONE_PLUTO)
val ANY_MAGICAL_WOOD = UTWildcardMaterial(Identifier(MODID, "any_magical_wood"), SILVERWOOD, LIVINGWOOD, DREAMWOOD, SHIMMERWOOD, GREATWOOD)
val ANY_FLOUR = UTWildcardMaterial(Identifier(MODID, "any_flour"), POTATO, WHEAT, BARLEY, RYE, OAT)

val WILDCARD_MATERIALS = arrayListOf(ANY_IRON_STEEL, ANY_ASHES, ANY_BRONZE, ANY_CALCITE, ANY_CARBON, ANY_CLAY, ANY_COAL_CARBON, ANY_COPPER, ANY_DEFAULT_WOOD,
        ANY_DIAMOND, ANY_EMERALD, ANY_FLOUR, ANY_FLOUR_OR_GRAINS, ANY_GARNET, ANY_GLOWSTONE, ANY_GRAINS, ANY_IRON, ANY_IRON_OR_STEEL, ANY_MAGICAL_WOOD,
        ANY_METAL, ANY_NORMAL_WOOD, ANY_PRISMARINE, ANY_SALT, ANY_SAPPHIRE, ANY_SILICON, ANY_SILICON_DIOXIDE, ANY_STEEL, ANY_STONE, ANY_THAUMIC_CRYSTAL, ANY_TREATED_WOOD,
        ANY_TUNGSTEN, ANY_UNTREATED_WOOD, ANY_WAX, ANY_WOOD, ANY_WOOD_OR_PLASTIC, ANY_QUARTZ)
